### ISSUE TITLE
History page not working?

### ISSUE THREAD

**Issue by FuturrCoder** [alexander-ding/qotw#5]
When I click on history, it tries to load and then goes back to the home page.
What happens:
![Screen Recording 2020-09-14 at 4 21 39 PM](https://user-images.githubusercontent.com/33908899/93134360-ad41dc00-f6a6-11ea-8096-b8b16fe64112.gif)

**Comment by alexander-ding** [comment]
Hmm, this is really weird. I'm not seeing that at all when I log in.

**Comment by alexander-ding** [comment]
```
if (!isLoaded(auth) || !isLoaded(profile) || !data) {
    return <SplashScreen/>
  } else {
    if (!profile.isModerator) {
      history.push("/")
    }
  }
```
Just checked the code base. Could you check if this account is actually a moderator (isModerator should be true in the users Firestore collection)?

**Comment by alexander-ding** [comment]
Ok. The isModerator check just shouldn't exist. My bad: didn't catch this bug. I've pushed a commit to master. The production code base should reflect the change in a few minutes
